const loaderConstants = {
  LOADER_START_REQUEST: 'LOADER_START_REQUEST',
  LOADER_START_SUCCESS: 'LOADER_START_SUCCESS',
  LOADER_STOP_REQUEST: 'LOADER_STOP_REQUEST',
  LOADER_STOP_SUCCESS: 'LOADER_STOP_SUCCESS',
  LOADER_STOP_FAILURE: 'LOADER_STOP_FAILURE',
};

export default loaderConstants;
