export const transcriptConstants = {
  GENE_INFO_REQUEST: 'GENE_INFO_REQUEST',
  GENE_INFO_SUCCESS: 'GENE_INFO_SUCCESS',
  GENE_INFO_FAILURE: 'GENE_INFO_FAILURE',
  GET_TRANSCRIPT_REQUEST: 'GET_TRANSCRIPT_REQUEST',
  GET_TRANSCRIPT_SUCCESS: 'GET_TRANSCRIPT_SUCCESS',
  GET_TRANSCRIPT_FAILURE: 'GET_TRANSCRIPT_FAILURE',
  GENE_INFO_RESET: 'GENE_INFO_RESET',
};